#!/bin/bash

# This script builds all tools automatically.
# The versions are known to work.

./uscan/build 2.22
./gnuplot/build 5.4
./pigz/build 2.6
./python3/build 3.10
./gfacpp/build 0.1
./dfam-tetools/build 1.88.5
./hifiasm/build 0.19.8
./hifiasm/build 0.19.9
./verkko/build 2.1
./seqkit/build 2.4.0
./seqkit/build 2.8.1
./minimap2/build 2.28
./gfastats/build 1.3.6
./liftoff/build 1.6.3
./mashmap/build 3.1.3
./yak/build 0.1
./merqury/build 1.3
./nanocomp/build 1.20.0
./seqtk/build 1.4
./samtools/build 1.19.2

echo "Run this now or to your ~/.bashrc file to access modules:"
echo "export MODULEPATH=`pwd | awk -F'/build_containers' '{print $1}'`/modulefiles:\$MODULEPATH"
